### PR TITLE
Two pattern implementations

### PR DESCRIPTION
**Pull request by feclist**
Implemented the factory pattern on driver and powerup. Also implemented observer pattern on all the collisions. Collisions are now handled from within the driverheart and called with collisions.allCollisions() from there you can trace down the way the observers are handled. Also the player doesn't hold powerups anymore. Powerups are handled in threads that have a timer.

<performance,organization,interface,naming,logic

### CODE REVIEW

**Comment by Ishadijcks** [comment]
Next time, please create both patterns on seperate branches

**Comment by feclist** [comment]
They were so badly intertwined, it would've been hard to do this in separate branches

**Comment by Ishadijcks** [comment]
Why are the driver instantiated with an empty string as parameter?

**Comment by Ishadijcks** [comment]
Most of the code looks good, I'll run it tomorrow before I can merge it

**Comment by boninggong** [comment]
Some tests seems to fail due to the current changes. Your code looks good! If you can fix the failing tests, then I will merge it.

**Comment by feclist** [comment]
Fixed all the thangs and fixed the tests

**Comment by TimBuckers** [comment]
The are missing comments and some check style warnings caused by wrong spacing.
Can you take a look at the method shootRope from Player, I think it can be improved

**Comment by TimBuckers** [comment]
Only look at the shootRope method the other things are adjusted now and in my opinion good.

**Comment by boninggong** [comment]
Good job fixing the tests! Tim also removed the warnings and added Javadoc I saw. I think it is now ready to merge finally! :)

**Comment by boninggong** [comment]
Many changes floris! Such good patterns implemented :+1:  I will merge it now.

**Pull request merged**
