### PR TITLE
Refactor settings

### PR DESCRIPTION
**Pull request by Ishadijcks**
Split the data class settings into many smaller classes, grouped by category. Refactored the methods to now call the correct class

### CODE REVIEW

**Comment by Ishadijcks** [comment]
Travis build fails

**Comment by Ishadijcks** [comment]
Fixed the travis build by removing a faulty jUnit import

**Comment by boninggong** [comment]
I have checkout the branch and everything is still working fine. Each class is now responsible for a part of the settings which  make it more responsibility driven. Good job refactoring the settings Isha! 
Did you run the In-Code application again? I think it shouldn't give a warning about a data class anymore, but you never know..
If you will do that and it will not give warnings about data classes anymore, then you can merge!

**Comment by TimBuckers** [comment]
I belief there are missing java doc in the settings classes

**Comment by TimBuckers** [comment]
Can you run all the tests? testCheckCollisionRope in RopeBubbleCollision gives an error.

**Comment by feclist** [comment]
Nice move changing the settings to separate classes! All the tests seem to work now :+1:

**Pull request merged**
