### PR TITLE
Levels contains moving wall now <feature

### PR DESCRIPTION
**Pull request by boninggong**

### CODE REVIEW

**Comment by TimBuckers** [comment]
Travis build fails, but nice the new levels with increasing difficulty.
Fix the build then it's ready to merge

**Comment by boninggong** [comment]
Can you help me with this please? I don't know where the errors come from and can't fix them.

**Comment by boninggong** [comment]
Ah stupid bug that I didn't saw! Thanks for helping! I will merge the changes now

**Comment by feclist** [comment]
Everything seems to work :), good job :+1:

**Pull request merged**
