### PR TITLE
Fixing observers

### PR DESCRIPTION
**Pull request by feclist**

### CODE REVIEW

**Comment by TimBuckers** [comment]
The fix looks good even parameterized tests work on the build.

**Comment by TimBuckers** [comment]
Only there is a nullpointer exception

**Comment by TimBuckers** [comment]
Succes builds now, the pull request is ready for merging!

**Comment by boninggong** [comment]
Looking good, I also think that the previous implementation was good enough, but this one is the right one according to Maiko. So good that you have refactored it :+1:

**Pull request merged**
