### PR TITLE
Fix checkstyle warnings

### PR DESCRIPTION
**Pull request by TimBuckers**
Al most all warnings removed, floris can you look at the merge ?

### CODE REVIEW

**Comment by feclist** [comment]
The build is failing because of a compilation error. Fix this before this branch is ready to merge :+1:

**Comment by boninggong** [comment]
Merge that bitch

**Comment by boninggong** [comment]
image
wow, such conflicts, much merging

**Comment by feclist** [comment]
How i can merge when no succes build :8ball:

**Comment by boninggong** [comment]
Tim merge harder

**Comment by feclist** [comment]
Build works now, sooooo sexy :+1:

**Pull request merged**
