### PR TITLE
Split collisions into subclasses to fix inCode error

### PR DESCRIPTION
**Pull request by feclist**
Also made dragons loose lifes when hit by bubble <organisation,bug

### CODE REVIEW

**Comment by Ishadijcks** [comment]
Ishadijcks/SEMgroup32/src/test/java/CollisionsTest.java:[12,31] game.collisions.Collision is abstract; cannot be instantiated

**Comment by Ishadijcks** [comment]
That was fast

**Comment by Ishadijcks** [comment]
I like the way you split the observers and the collision handling. inCode appreciates it too, almost all design flaws disappeared or are greatly reduced. Add some javaDoc to all the newly created methods and I can accept it

**Comment by TimBuckers** [comment]
I added the comments and I agree with the other things. So this branch is fully ready to merge.

**Comment by boninggong** [comment]
Looks good boys, the few small issues are also fixed I see! You I will merge it now :+1:

**Pull request merged**
